require 'clipreasy/engine/markable'
require 'clipreasy/engine/statement'
require 'clipreasy/engine/activity'
require 'clipreasy/engine/when'
require 'clipreasy/engine/decision'
require 'clipreasy/engine/parallel'
require 'clipreasy/engine/sequence'
require 'clipreasy/engine/until'
require 'clipreasy/engine/while'
require 'clipreasy/engine/process'

require 'clipreasy/engine/process_xml_decoder'

require 'clipreasy/engine/process_context'
require 'clipreasy/engine/default_process_context'
require 'clipreasy/engine/backend_process_context'
